spring.application.name=PostService
spring.datasource.url=${spring_datasource_url}
spring.datasource.username=${spring_datasource_username}
spring.datasource.password=${spring_datasource_password}
spring.datasource.driver-class-name=${spring_datasource_driver_class_name}


spring.jpa.hibernate.ddl-auto=${spring_jpa_hibernate_ddl_auto}
spring.jpa.show-sql=${spring_jpa_show_sql}
spring.jpa.properties.hibernate.dialect=${spring_jpa_properties_hibernate_dialect}


server.port=1000